C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C                                                                  
C Sparse Stoichiometric Data Structures File                       
C                                                                  
C Generated by KPP-3.0.0-rc.2 symbolic chemistry Kinetics PreProcessor
C       (https:/github.com/KineticPreProcessor/KPP                 
C KPP is distributed under GPL, the general public licence         
C       (http://www.gnu.org/copyleft/gpl.html)                     
C (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
C (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech            
C     With important contributions from:                           
C        M. Damian,   Villanova University, Philadelphia, PA, USA  
C        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
C        M. Long,     Renaissance Fiber, LLC, North Carolina, USA  
C        H. Lin,      Harvard University, Cambridge, MA, USA       
C        R. Yantosca, Harvard University, Cambridge, MA, USA       
C                                                                  
C File                 : small_strato_StoichiomSP.f                
C Equation file        : small_strato.def                          
C Output root filename : small_strato                              
C                                                                  
C ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




C Row-compressed sparse data for the Jacobian of reaction products JVRP
      BLOCK DATA JVRP_SPARSE_DATA

      INCLUDE 'small_strato_Sparse.h'
      INTEGER i

      DATA CROW_JVRP /
     *  1,  1,  2,  3,  5,  6,  7,  9, 11, 13, 14 / 


      DATA ICOL_JVRP /
     *  2,  3,  2,  3,  3,  1,  1,  3,  3,  4,  2,  5,
     *  5 / 


      DATA IROW_JVRP /
     *  2,  3,  4,  4,  5,  6,  7,  7,  8,  8,  9,  9,
     * 10 / 


      END




C  Stoichiometric Matrix in Compressed Column Sparse Format        

      BLOCK DATA STOICM_MATRIX

      INCLUDE 'small_strato_Sparse.h'
      INTEGER i

      DATA CCOL_STOICM /
     *  1,  2,  4,  6,  8, 10, 12, 14, 17, 20, 23 / 


      DATA IROW_STOICM /
     *  2,  2,  3,  2,  3,  2,  3,  1,  3,  1,  2,  1,
     *  3,  3,  4,  5,  2,  4,  5,  2,  4,  5 / 


      DATA ICOL_STOICM /
     *  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,
     *  7,  8,  8,  8,  9,  9,  9, 10, 10, 10 / 


      DATA STOICM /
     *    2,   -1,    1,    1,   -1,   -1,   -1,    1,
     *   -1,   -1,    1,   -1,   -1,   -1,   -1,    1,
     *   -1,    1,   -1,    1,    1,   -1 / 


      END


